### ISSUE TITLE
Annotated list of SRA libraries with known Coronaviruses

### ISSUE THREAD

**Issue by mathemage** [ababaian/serratus#16]
Create an annotated list of SRA libraries with known Coronaviruses in the samples (i.e. SARS cell culture, SARS-CoV-2 accessions).

_Originally posted by @ababaian  in 
https://github.com/ababaian/serratus/issues/5#issue-589616145_

**Comment by mathemage** [comment]
@jefftaylor42 @ababaian 
* What do you mean by "annotated" in "annotated list"?
* How should this be stored?
  * Simple text file? 
  * Markdown document? 
  * Database?

**Comment by mathemage** [comment]
@jefftaylor42 @ababaian I suggest adding tag Bioinformatics to this issue.

**Comment by ababaian** [comment]
@victorlin is working on this currently

**Comment by victorlin** [comment]
[SRAdb](https://doi.org/10.1186/1471-2105-14-19) seems to be a good source of metadata. Here is a quick example search using Python wrapper [pysradb](https://github.com/saketkc/pysradb) (there are more columns cut off):

<img width="913" alt="Screen Shot 2020-04-02 at 5 48 44 PM" src="https://user-images.githubusercontent.com/13424970/78303229-466ea300-750a-11ea-897e-07a25d32d8a9.png">

Some things to consider:

1. What information are we looking for - just accession IDs or some other features that come with?
2. Compile a list of relevant search terms (ex. `SARS`, `MERS`, `Cov-2`, `ncov`, etc)

**Comment by victorlin** [comment]
Rather than a potentially sparse list of search terms, an exhaustive search could be achieved by backwards-searching a NCBI taxonomy entry for SRA samples (e.g. [Taxnonomy entry for Betacoronavirus](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Undef&id=694002&lvl=3&keep=1&srchmode=1&unlock), [respective Entrez query](https://www.ncbi.nlm.nih.gov/biosample/?term=txid694002[Organism:exp]))

**Comment by ababaian** [comment]
Now that's a fantastic idea!

**Comment by superbsky** [comment]
@victorlin please also consider programmed access to the ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz via https://github.com/frallain/NCBI_taxonomy_tree

it can do nice tricks and be combined with the SRAdb queries in the Python code

**Comment by victorlin** [comment]
Here is a [Jupyter notebook](https://gist.github.com/victorlin/a9704d74f03bcbf35cc3e03e68c4b0b5) showing the process of retrieving metadata for all SRA experiments under [Coronaviridae](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=11118).

I used [`biopython`](https://github.com/biopython/biopython)'s Entrez API to get SRA accession IDs under the Taxonomy listing, followed by [`pysradb`](https://github.com/saketkc/pysradb)'s SRAdb API to fetch metadata.

@ababaian if this is sufficient, let me know how I should share the data; otherwise please advise if any other information is needed :)

**Comment by ababaian** [comment]
Hey @victorlin this looks great. I think using jupyter notebook / RMD files to track experiments and/or analyses is the way to go moving forward : ) This way we can keep track of what work has been done.

Can you copy over your script using the template available in `serratus/notebook/200401_template.ipynb`. For the output table, this belongs in `serratus/data/sra` in the format of an `SraRunInfo.csv` table. And one last thing would be to add a link to the notebook file to the `serratus/data/README.md` under `sra`. You should have push access to the repo now.

**Comment by ababaian** [comment]
Hey @victorlin,

This is great! Right now we're

**Comment by victorlin** [comment]
@ababaian ah, if all that's needed is a `SraRunInfo.csv` of SRA runs under Coronaviridae, that file can be downloaded from the [query page](https://www.ncbi.nlm.nih.gov/sra/?term=txid11118[Organism:exp]) directly without any scripting. Wish I had thought of that earlier 😅

I'll make all those edits including the notebook file anyways, since it seems to capture slightly different information than `SraRunInfo.csv`. Could be useful in the future.

**Comment by ababaian** [comment]
See also https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE147507

**Comment by ababaian** [comment]
See also #34 

These issues are related, but we can consider this 'done' at least at the superficial level until we resolve the WGS issue as well.

**Comment by rcedgar** [comment]
Question / new issue / related issue: Do we know any examples of the runs we're trying to find, i.e. human RNA-seq with captured Cov? If I have some, then I can train a quick-and-dirty test to discriminate candidate runs from the background. If we don't know of any, then do we know / can we find any runs with viruses in other families? Those could be used as a model, though this would be a lot more work because we'd have to make new pan-genomes. If we're totally flying blind, then I can make something to sort runs completed so far in order of most promising candidates for manual analysis so that we can monitor until we find some.

**Comment by ababaian** [comment]
We have a compiled list of libraries which should be CoV positive [here](https://serratus-public.s3.amazonaws.com/sra/coronaviridae_SraRunInfo.csv)

From an older test these accessions have lots of SARS-CoV-2 reads

```
# CoV+ Control Libraries
SRR11454606	4108
SRR11454607	23362
SRR11454608	184454
SRR11454609	67683
SRR11454610	127472
SRR11454611	3597
SRR11454612	6918
SRR11454613	873824
SRR11454614	1894336
SRR11454615	124702
```
