### ISSUE TITLE
Phylogenetic and taxonomic analyses for any viral contigs

### ISSUE THREAD

**Issue by eul2021** [ababaian/serratus#258]
Hello,

I was wondering if currently phylogenetic & taxonomic analyses are only for  RdRP or could be used for nt of any viral contigs?

Thank you.

**Comment by rcedgar** [comment]
For Coronavirus assemblies we attempted to predict taxonomy for nt contigs where we could find CDS, for the translated search for RdRP the analysis is based on palmprints only. If you can you explain a bit more what you are trying to do, we'll be glad to help if we can.

**Comment by eul2021** [comment]
Robert, thank you for the quick response. Let's say I have a nt contig (either whole genome, or one/two protein) of a putatively novel non coronavirus and I want to place it to the overall viral phylogenetic tree, or to a specific branch X. Is there currently support for that?

**Comment by rcedgar** [comment]
Our approach for this is to run palmscan (https://github.com/rcedgar/palmscan) to find a palmprint (barcode sequence in RdRP). If one is found, then we align to OTUs in palmdb (https://github.com/rcedgar/palmdb, otu_centroids.fa) using usearch_global at 90% identity. This does not place in a tree per se. If the palprint is within a known family, then you can make a palmprint MSA using muscle v5 and raxml to build the tree. Otherwise it's technically quite difficult to place a palmprint.

**Comment by rcedgar** [comment]
So I think the answer to the main question is that we use RdRP only for classification because it's the only gene shared across the large majority of RNA viruses. Other genes are informative of course, but only within smaller groups. Our goal with Serratus was to develop a classification scheme that was transparent. simple and robust across all RNA viruses; we feel that palmprints are a good solution for this but of course they are not a complete solution for defining RNA virus taxonomy from sequence.
