### ISSUE TITLE
Hard Optimize `bowtie2` alignment parameters

### ISSUE THREAD

**Issue by ababaian** [ababaian/serratus#35]
### Problem:
We are currently running `bowtie2 --very-sensitive-local ...` for detecting homologous CoV sequences. We need a method (script) to test an array of `bowtie2` parameters for time, sensitivity and specificity of alignment.

Current settings are `-D 20 -R 3 -N 0 -L 20 -i S,1,0.50`, say we'd like to test the space of `-D 5-25 -R 1-4 -N 0-1 -L 30-15`.

### Test Data
We will have simulated data soon for benchmarking but for now we can use some real data. You can likely sub-sample these to ~100,000 from CoV+ and 100,000 form CoV- for coarse-grain optimization and then do a few ultra-deep libraries in a smaller search space.
- [CoV Reads from SRR11454614](https://serratus-out.s3.amazonaws.com/out/bam/SRR11454614.bam)
- Mouse CoV negative SRR9658384 / SRR9658385

### Output
The output should be

1) Wall-clock / CPU time / User time for each setting.
2) TP / FP / TN / FN

#### See Also

- [bowtie2 manual](http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml)

**Comment by rcedgar** [comment]
Suggest better would be to use hold-out cross-validation as described in Issue #48 because positive controls are too easy and will give a highly overestimated TP rate compared to the real task.

Minor comment, but timing is probably not informative because bowtie2 will probably not be the compute bottleneck in which case we should optimize by accurate not speed. Also because I suspect true positive datasets (novel strains) will be very rare and hard to find.

**Comment by rcedgar** [comment]
Suggest comparing paired and unpaired modes per Issue #50.

**Comment by ababaian** [comment]
We're 3 million deep, this probably won't happen. We can come back to it if needbe.
