### ISSUE TITLE
Why just Cov?

### ISSUE THREAD

**Issue by rcedgar** [ababaian/serratus#49]
Seems to me we have a workflow which can be expanded to include many more families of virus with a small incremental effort. In terms of EC2 resources, there would be negligible additional cost because bowtie2 can map to a 3Gb pan-genome at similar speed to a 30Mb pan-genome. Why not leverage the big compute to capture as many novel viruses as possible?

**Comment by ababaian** [comment]
This 100% is the long-term goal, CoV is the most important family currently and it's mentally tractable. I am thinking we expand soon-ish to all [nidoviruses](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Undef&id=76804&lvl=3&lin=f&keep=1&srchmode=1&unlock)

The issue is that once you go into different viruses, you run into very large alignment issues. Retroviruses are next to impossible to distinguish from endogenous retroviruses, pox-viruses have some very host-like genes.

**Comment by rcedgar** [comment]
If you construct a large bulk dataset with all the viruses on your wish list, including poxes and whatever, I will undertake to screen them against human genome & transcripts to deal with FP hits. I expect I could do this within a few days.

**Comment by ababaian** [comment]
Mega0 genome is now integrated. We are scanning for all human emerging pathogens in first pass.
