### ISSUE TITLE
Summarizer implementation

### ISSUE THREAD

**Issue by rcedgar** [ababaian/serratus#57]
I'm building a "summarizer" which sits in the pipeline after bowtie2 and generates a short report with information about the hits. The summary is human- and machine-readable.

SAM records are forwarded to the next stage in the pipe, which could redirect output to a SAM file, or forward samtools to compress to BAM before saving, or whatever. In other words, the summarizer is similar to the Linux 'tee' command except that it writes a report when the pipeline completes.

Results from first attempt at summarizer for the 200423_ab_cov2r runs:

https://drive5.com/tmp/summaries.tar.gz

Update soon with 200423_ab_cov0r results.

**Comment by ababaian** [comment]
Example output from ERR2906843 (HCT116 Human cell line RNA-seq)
```

**Comment by ababaian** [comment]
Is it possible to include a seperate count for entries starting with `REVERSE` as this is the bait control sequence. The ratio of Real CoV: Reverse Bait is one QC measure we can make off the bat.
````
mapped={x}
mapped_reverse={y}
mapped_reverse_ratio={y/x}
...
```

**Comment by ababaian** [comment]
Taking a dive in these files there are some qualitative differences in the mapping. I'm not sure an on-pipe summarizer can handle this type of description but I'll put it here for now.

### SARSCOV2 reads aligned to SARSCOV2
There's good coverage over a wide area here. The coverage depth and therefore total number is high. Note how there are multiple foci of alignment, since mutations are not random (evolutionary conservation) we get a broader coverage here and note in the summary how many entries have reads over them.
![SARSCOV2_vs_SARSCOV2](https://user-images.githubusercontent.com/9220907/80269614-d5518400-86a0-11ea-9e48-26410aaba681.png)

# SARSCOV2 aligned against BAT SARS
This is most likely a misalignment and these reads belong to some SARSCOV2 sequence which may or may not be pruned.
![SARSCOV2_vs_BATSARS](https://user-images.githubusercontent.com/9220907/80269636-fa45f700-86a0-11ea-8ba5-1bd8a5d6b00e.png)
![SARSCOV2_vs_BATSARS_detail](https://user-images.githubusercontent.com/9220907/80269637-fca85100-86a0-11ea-8bfe-b912dc60bd12.png)

### Human RNA-seq vs. Infectious Bronchitis Virus
This is a false positive. There is a human gene LHR1 with a partial match to 18S rRNA sequence from a weird species. This can be either a contaminant rRNA in the sample or the homologous gene from Macai being expressed. Note the alignment is highly focal and occurs in only one spot.

![HCT116_vs_InfectiousBrochitisVirus](https://user-images.githubusercontent.com/9220907/80269677-5e68bb00-86a1-11ea-896e-4aaf9cdd9a21.png)
 
I think having this `summarizer` greatly speeds up where we need to look manually, we may need a bit more of an involved `classifier` for determining if a library is potentially CoV+ or CoV- and moving to subsequent assembly.

Or we assemble all libraries above a threshold % of hits and then align the contigs as the validation.

**Comment by rcedgar** [comment]
Reverse % will be included in next results, coming shortly.

It is straightforward to add coverage to the summarizer. I'm trying to do something quickly so that it can be included in the first production run.

Sounds like SSU RNA (18S/16S) should be excluded from the mapping reference?

**Comment by ababaian** [comment]
I thought about something like this but maybe it belongs closer to `bvfilter`, we can probably get a very (memory) cheap human/mammal filter if we just remove the most abundant RNA. rRNA, ribosomal protein genes, Actin, GAPDH, Metabolic genes. I think with a minority of transcripts we can remove a huge chunk of reads with almost no memory footprint. A little off topic here but something to keep in mind.

**Comment by ababaian** [comment]
You know we might also be overthinking this. If we learn after X runs that if a library only aligns to `KC786228.1` then we can just add that to an "ignore-list". I guess what we risk is that if we add something to the ignore list and it has a real match to that sequence. I think we need more data to make this call.

**Comment by rcedgar** [comment]
Exactly -- we should keep everything in the mapping reference if possible, the only reason to delete or mask something is if we're 100% sure it's not Cov or it has a substantial performance cost. It is very cheap to re-run summaries and downstream analysis.

**Comment by rcedgar** [comment]
Updated summaries uploaded to S3:

s3://serratus-public/out/200423_ab_cov0r/sum/
s3://serratus-public/out/200423_ab_cov2r/sum/

There are several new fields including len (sequence length), depth (naively defined as total_aligned_bases/length), pctid (self-explanatory) and a 16-character "cartoon" visualizing coverage along the sequence, e.g. "_...o.o..@OoO.o_". The five symbols are _.oO@ indicating coverage from zero (_) to max (@).

At this point, I would expect to upload source and documentation to new directories src/summarizer doc/summarizer. What's the equivalent procedure in the serratus repo?

**Comment by ababaian** [comment]
`src/summerizer/summerizer` and `src/summerizer/README.md` once Jeff OKs the pull request so it doesn't break what he was working on.

**Comment by rcedgar** [comment]
Gotcha. Will close this issue now. If needed, further discussion of new features and bugs to be opened as new issues after source & docs posted.
